//
// Created by garri on 18.03.2022.
//

#ifndef UEBUNG_PRAKTISCHE_INFORMATIK_GENERAL_FUNCTIONS_H
#define UEBUNG_PRAKTISCHE_INFORMATIK_GENERAL_FUNCTIONS_H
int position_in_text(char *text_part, char *text);
#endif //UEBUNG_PRAKTISCHE_INFORMATIK_GENERAL_FUNCTIONS_H
